version: "3.7"

x-common:
  - &DB_ROOTPASS "passw0rd"
  - &DB_USER "people"
  - &DB_PASS "people"
  - &DB_NAME "people"
  - &DB_PORT 3306

services:
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: *DB_ROOTPASS
      MYSQL_DATABASE: *DB_NAME
      MYSQL_USER: *DB_USER
      MYSQL_PASSWORD: *DB_PASS
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
      MYSQL_INITDB_SKIP_TZINFO: 'yes'
      TZ: Tokyo/Asia
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - mysql:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"

  backend:
    image: kudoshunsuke/docker-people-management-backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    depends_on:
      - db
    tty: true
    command: yarn start
    entrypoint: /entrypoint.sh
    environment:
      DB_NAME: *DB_NAME
      DB_USER: *DB_USER
      DB_PASS: *DB_PASS
      DB_HOST: db
      DB_PORT: *DB_PORT
      TESTING: 1
      TZ: Tokyo/Asia
    volumes:
      - ./backend/entrypoint.sh:/entrypoint.sh:ro
      - ./backend/ormconfig.org.js:/home/node/app/ormconfig.org.js:ro
      - ./backend/package.json:/home/node/app/package.json
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
      - ./backend/src:/home/node/app/src
    ports:
      - "14000:4000"

  frontend:
    image: kudoshunsuke/docker-people-management-frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    tty: true
    command: bash
    ports:
      - "18080:4200"
    volumes:
      - ./frontend/src:/home/node/frontapp/src
      - ./frontend/package.json:/home/node/frontapp/package.json
      - ./frontend/tsconfig.json:/home/node/frontapp/tsconfig.json

volumes:
  mysql:
    driver: "local"

